# Generated by Django 4.1.7 on 2023-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0002_rename_titulos_servico_titulo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="identificador",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
